---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: code-server-cm 
  namespace: code-serverns 
data: 
  TZ: Asia/Singapore 
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-146.190.6.174.nip.io

--- 
apiVersion: v1 
kind: Secret
metadata: 
  name: code-server-secret 
  namespace: code-serverns
type: Opaque
data: 
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
